### ISSUE TITLE
Linux port + Packaging

### ISSUE THREAD

**Issue by damageboy** [nosmokingbandit/AluminumFoil#16]
Hi,
I've managed to get AluminumFoil to run on Linux (the "Mac" version), with some minor tweaks.

There are still some Avalonia related issues that need resolving, and I'm working on it...

Would you, in general, be OK with me contibuting a azure-pipelines script to generate artifacts (.deb / .tar.xz for linux, .app for macos and .exe for windows) and renaming AluminumFoil.Mac to AluminumFoil.Posix or something like that?

If OK, I'll try to work out a PR for this...

**Comment by nosmokingbandit** [comment]
Go for it.

I don't have access to a linux machine I can install the dotnet core sdk on (just an low-powered headless server at home but that seems like a giant headache) but I would expect the Avalonia gui would build and run with minimal adjustments. Avalonia can be a bit of a pain because the documentation is pretty rough so don't hesitate to ask me for pointers.

**Comment by damageboy** [comment]
Thanks for the offer.
But I think I'm pretty much good now.
I did have to update the Avalonia for Linux (And I might do it again later today) as the autosizing feature might be fixed to today.

Everything is working pretty much...
I did some minor tweaks all in all...l

I'm working now on producing a proper debian/ubuntu package, as apparently you need to generate a udev/rules.d file to be able to access the switch from Linux without root permissions....

Looks like I'll be able to make it happen... :)

**Comment by damageboy** [comment]
Hey, I think I have everything ready/working for merge.

I'll soon submit a PR, but I'd really also like to move the project to structure where the official release gets built from the master branch, while commits go into a "dev" branch if it's OK with you?

This way I can then move on to integrating with azure pipelines so that every commit gets built wherever is necessary...

Would it be possible for you to merge my commits as a dev branch for now?

**Comment by damageboy** [comment]
Thanks for merging!
