### ISSUE TITLE
How do I launch the .darwin file for mac?

### ISSUE THREAD

**Issue by Johnny165** [nosmokingbandit/AluminumFoil#2]
Hello, how would I open the .darwin file from the releases page on macos? I've tried searching this file up online and haven't found documentation of this file type (Maybe I'm not looking at the right place, not sure...)

**Comment by nosmokingbandit** [comment]
You can run with `./AluminumFoild.Darwin` in a terminal. I don't have a mac handy, but I don't think it will open with a double-click in Finder.

Fwiw, I'd like to make an app package for it but I'm not getting too excited about anything until the drama and nonsense dies down (if it ever does).

Maybe if GoldLeaf gets an actual release I'll make it more user-friendly. I'm not committing a lot of time to something that might be abandoned already.

**Comment by nosmokingbandit** [comment]
Apparently you just rename it to `aluminumfoil` and it will then open with a double-click. I'm going to rename the release so the `.darwin` at the end doesn't confuse osx.

**Comment by Johnny165** [comment]
Thank you!

**Comment by Johnny165** [comment]
Just tried it on terminal and it still doesn't work... :/
I was able to double-click it to open up terminal but it doesn't run for some reason.
