### ISSUE TITLE
Number of installations are limited by screen size

### ISSUE THREAD

**Issue by Sheeraudacity** [nosmokingbandit/AluminumFoil#21]
Trying to install more than 17 titles will result in aluminium foil's install button disappearing into the abyss.At lower resoultions the number is even lower, the number of installations shouldn't be tied with the screen size. Maybe an option to scroll down should be added.

<img width="288" alt="aluminium-foilpic" src="https://user-images.githubusercontent.com/28789170/54865248-b3861f00-4d73-11e9-8e73-fe53906414d1.png">

**Comment by TehPsychedelic** [comment]
I'll actually piggyback on this issue. Is there any technical/design reason why window resize is restricted? Asides from the issue described above, it's also annoying not to see the entire file name when several are opened (e.g multiple DLC of same game) and if you use the silent scene standard to rename your dumps then you end up having 3 or 4 rows with same base name so no way to know which one is what.

**Comment by nosmokingbandit** [comment]
> Is there any technical/design reason why window resize is restricted? 

Because it is kind of a pain in the ass. But I did it anyway. Because I love you all. Or something.

https://github.com/nosmokingbandit/AluminumFoil/releases/tag/1.0.0.9

**Comment by TehPsychedelic** [comment]
Sorry but window width still restricted not as in the release notes, at least for me on windows10.
It also keeps going to the abyss.
Maybe i'll try to compile master later and check.

**Comment by nosmokingbandit** [comment]
Check the releases page again. Apparently I have a hard time telling the difference between 8 and 9. To be fair, they *are* very close to each other.

**Comment by TehPsychedelic** [comment]
Thank you, I tried to compile it last night but it only fueled my hatred for NuGet even more.
Tested it and working fine. It looks a bit funky since you can resize height but it stays on scroll block size but well, protip: just use the scroll.

![image](https://user-images.githubusercontent.com/21700114/55190229-6dfb9480-516d-11e9-9da5-dda1c8e72e6d.png)

**Comment by nosmokingbandit** [comment]
Huh. That doesn't happen for me. What windows version are you using?

**Comment by TehPsychedelic** [comment]
Windows 10 Pro 17134. I'll update to next one (latest) and check.

**Comment by nosmokingbandit** [comment]
No need to update (i know how much of a pain that can be). I'll get a
hotfix out tomorrow.

**Comment by TehPsychedelic** [comment]
I updated anyway and yes indeed same issue. Thanks for the upcoming hotfix.

**Comment by Sheeraudacity** [comment]
I have done some testing on it and the scroll works perfectly. There's an apparent limit on how much files tinfoil can install pushing more than about 24 causes screen shutter and a reboot. I am closing this since the scroll works perfectly for the intended use
