### ISSUE TITLE
how to open "AluminumFoil" on mac

### ISSUE THREAD

**Issue by wendyliga** [nosmokingbandit/AluminumFoil#3]
how to open AluminumFoil on mac , there is a darwin release , and i cannot open it on my mac

**Comment by mattchue** [comment]
`chmod +x AluminumFoil_Darwin`
`./AluminumFoil_Darwin`

**Comment by wendyliga** [comment]
wow , it's works 

it's so strange , previously i tried to change the permission and it still didn't 

but regardless of that , it works now

thanks @mattchue

**Comment by wendyliga** [comment]
also i forgeted to read previous closed issue

there is same problem at https://github.com/nosmokingbandit/AluminumFoil/issues/2

my bad
