### ISSUE TITLE
Multiple install  error

### ISSUE THREAD

**Issue by JoshuaBacurioMercado** [nosmokingbandit/AluminumFoil#6]
When I install one nsp it works, but when I install multiple nsp at the same time, they all get corrupted and show up with no picture on home page, and in data management showing 0 mb

**Comment by nosmokingbandit** [comment]
I'm closing this since the project has moved on to a completely different codebase. I've never done multi-installs on TinFoil, but we should all be using GoldLeaf now anyway.
