### ISSUE TITLE
Download Progress 0/0

### ISSUE THREAD

**Issue by bonezinger** [nosmokingbandit/AluminumFoil#7]
I'm trying to install a nsp, but it never works. My tinfoil is 0.2.1, running on ReiNX for firmware 6.2.
I'm running the aluminum on windows 10, I can find and send the listed nsp to the switch, but once i select it and press A to begin, the download is simply stuck at 0

These are the lines that show on the command prompt after "Waiting for Switch"
Piece Size: 16, Piece Offset: 0, Name Len: 67, Name: d:\torrents\xxx.nsp
Piece Size: 320, Piece Offset: 16, Name Len: 67, Name: d:\torrents\xxx..nsp

**Comment by exJad** [comment]
I had the same problem, and fixed it by getting an older version of tinfoil
[tinfoil.zip](https://github.com/nosmokingbandit/AluminumFoil/files/2809795/tinfoil.zip)

**Comment by zouyonghao** [comment]
> I had the same problem, and fixed it by getting an older version of tinfoil
> [tinfoil.zip](https://github.com/nosmokingbandit/AluminumFoil/files/2809795/tinfoil.zip)

Perfect!
