### ISSUE TITLE
0x1 Error

### ISSUE THREAD

**Issue by sadboychaz** [nosmokingbandit/AluminumFoil#8]
Tinfoil has been crashing through python. I figured I'd give aluminum foil a shot... to no avail. When i try it out, it gives me a bunch of lines with 0x1 and crashes my switch. Nsp folder only has one file inside of it.

**Comment by nosmokingbandit** [comment]
Make sure you are using an older version of TinFoil. I think the build around mid-October is the latests that works.

I'm closing this since the codebase has changed to only work with GoldLeaf now anyway.
